-- 本檔由 cpami-form-editor/tools/gen_db_views.py 產生，請勿手動編輯。
-- JSONB payload 是正本；下列 view 只提供 text、numeric 與日期查詢投影。

CREATE OR REPLACE VIEW cpami_v_bmsbase AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'BMPAS' AS bmpas,
    r->>'BUILDING_CATEGORY' AS building_category,
    r->>'BUILDING_NAME' AS building_name,
    r->>'PUBLIC_CODE' AS public_code,
    r->>'LAND_NUM' AS land_num,
    r->>'BUILDING_LINE_WORD' AS building_line_word,
    r->>'BUILDING_LINE_NO' AS building_line_no,
    r->>'BUILDING_DATE' AS building_date,
    cpami_roc_to_date(r->>'BUILDING_DATE') AS building_date_date,
    r->>'LAW_COVER_RATE' AS law_cover_rate,
    NULLIF(r->>'LAW_COVER_RATE', '')::numeric AS law_cover_rate_num,
    r->>'LAW_SPACE_RATE' AS law_space_rate,
    NULLIF(r->>'LAW_SPACE_RATE', '')::numeric AS law_space_rate_num,
    r->>'LAW_COVER_RATE_DESC' AS law_cover_rate_desc,
    r->>'LAW_SPACE_RATE_DESC' AS law_space_rate_desc,
    r->>'BASE_AREA_ARC' AS base_area_arc,
    NULLIF(r->>'BASE_AREA_ARC', '')::numeric AS base_area_arc_num,
    r->>'BASE_AREA_SHRINK' AS base_area_shrink,
    NULLIF(r->>'BASE_AREA_SHRINK', '')::numeric AS base_area_shrink_num,
    r->>'BASE_AREA_OTHER' AS base_area_other,
    NULLIF(r->>'BASE_AREA_OTHER', '')::numeric AS base_area_other_num,
    r->>'BASE_AREA_PURPOSE' AS base_area_purpose,
    NULLIF(r->>'BASE_AREA_PURPOSE', '')::numeric AS base_area_purpose_num,
    r->>'BASE_AREA_TOTAL' AS base_area_total,
    NULLIF(r->>'BASE_AREA_TOTAL', '')::numeric AS base_area_total_num,
    r->>'STATUTORY_OPEN_SPACE' AS statutory_open_space,
    NULLIF(r->>'STATUTORY_OPEN_SPACE', '')::numeric AS statutory_open_space_num,
    r->>'USE_CATEGORY_CODE1' AS use_category_code1,
    r->>'USE_CATEGORY_CODE2' AS use_category_code2,
    r->>'USE_CATEGORY_CODE3' AS use_category_code3,
    r->>'BUIL_AREA_ARC' AS buil_area_arc,
    NULLIF(r->>'BUIL_AREA_ARC', '')::numeric AS buil_area_arc_num,
    r->>'BUIL_AREA_OTHER' AS buil_area_other,
    NULLIF(r->>'BUIL_AREA_OTHER', '')::numeric AS buil_area_other_num,
    r->>'USAGE_CODE' AS usage_code,
    r->>'USAGE_CODE_DESC' AS usage_code_desc,
    r->>'BUILDING_HEIGHT' AS building_height,
    NULLIF(r->>'BUILDING_HEIGHT', '')::numeric AS building_height_num,
    r->>'BUILDING_AREA' AS building_area,
    NULLIF(r->>'BUILDING_AREA', '')::numeric AS building_area_num,
    r->>'TOTAL_CONSTRU_AREA' AS total_constru_area,
    NULLIF(r->>'TOTAL_CONSTRU_AREA', '')::numeric AS total_constru_area_num,
    r->>'BUILD_COVER_RATE' AS build_cover_rate,
    NULLIF(r->>'BUILD_COVER_RATE', '')::numeric AS build_cover_rate_num,
    r->>'SPACE_RATE' AS space_rate,
    NULLIF(r->>'SPACE_RATE', '')::numeric AS space_rate_num,
    r->>'PRICE' AS price,
    NULLIF(r->>'PRICE', '')::numeric AS price_num,
    r->>'BUILDING_KIND1' AS building_kind1,
    r->>'BUILDING_KIND2' AS building_kind2,
    r->>'BUILDING_KIND3' AS building_kind3,
    r->>'BUILDING_BASE_KIND' AS building_base_kind,
    r->>'CHWANG_NO' AS chwang_no,
    NULLIF(r->>'CHWANG_NO', '')::numeric AS chwang_no_num,
    r->>'BUILDING_NO' AS building_no,
    NULLIF(r->>'BUILDING_NO', '')::numeric AS building_no_num,
    r->>'UP_FLOOR_NO' AS up_floor_no,
    NULLIF(r->>'UP_FLOOR_NO', '')::numeric AS up_floor_no_num,
    r->>'DN_FLOOR_NO' AS dn_floor_no,
    NULLIF(r->>'DN_FLOOR_NO', '')::numeric AS dn_floor_no_num,
    r->>'TOT_HOUSE_NO' AS tot_house_no,
    NULLIF(r->>'TOT_HOUSE_NO', '')::numeric AS tot_house_no_num,
    r->>'BUILD_HIHIGHT' AS build_hihight,
    NULLIF(r->>'BUILD_HIHIGHT', '')::numeric AS build_hihight_num,
    r->>'AIRRAID_U_AREA' AS airraid_u_area,
    NULLIF(r->>'AIRRAID_U_AREA', '')::numeric AS airraid_u_area_num,
    r->>'AIRRAID_D_AREA' AS airraid_d_area,
    NULLIF(r->>'AIRRAID_D_AREA', '')::numeric AS airraid_d_area_num,
    r->>'LAW_AIRRAID_AREA' AS law_airraid_area,
    NULLIF(r->>'LAW_AIRRAID_AREA', '')::numeric AS law_airraid_area_num,
    r->>'AIRRAID_P_AREA' AS airraid_p_area,
    NULLIF(r->>'AIRRAID_P_AREA', '')::numeric AS airraid_p_area_num,
    r->>'OTHERS_NAME' AS others_name,
    r->>'OTHERS_PRICE' AS others_price,
    NULLIF(r->>'OTHERS_PRICE', '')::numeric AS others_price_num,
    r->>'OTHERS_MEMO' AS others_memo,
    r->>'BASE_MEMO' AS base_memo,
    r->>'FILENAME' AS filename,
    r->>'APPLY_TYPE' AS apply_type,
    r->>'FIRST_TIME_DATE' AS first_time_date,
    cpami_roc_to_date(r->>'FIRST_TIME_DATE') AS first_time_date_date,
    r->>'FIRST_TIME_Desc' AS first_time_desc,
    r->>'FIRST_TIME_KNOW_DATE' AS first_time_know_date,
    cpami_roc_to_date(r->>'FIRST_TIME_KNOW_DATE') AS first_time_know_date_date,
    r->>'FIRST_TIME_KNOW_DESC' AS first_time_know_desc,
    r->>'APPROVE_LICE_DATE' AS approve_lice_date,
    cpami_roc_to_date(r->>'APPROVE_LICE_DATE') AS approve_lice_date_date,
    r->>'IDENTIFY_LICE_DATE' AS identify_lice_date,
    cpami_roc_to_date(r->>'IDENTIFY_LICE_DATE') AS identify_lice_date_date,
    r->>'IDENTIFY_LICE_OLD_DATE' AS identify_lice_old_date,
    cpami_roc_to_date(r->>'IDENTIFY_LICE_OLD_DATE') AS identify_lice_old_date_date,
    r->>'RECEIVE_LICE_DATE' AS receive_lice_date,
    cpami_roc_to_date(r->>'RECEIVE_LICE_DATE') AS receive_lice_date_date,
    r->>'RECEIVE_LICE_OLD_DATE' AS receive_lice_old_date,
    cpami_roc_to_date(r->>'RECEIVE_LICE_OLD_DATE') AS receive_lice_old_date_date,
    r->>'VALID_MONTH' AS valid_month,
    r->>'COMPLETE_DATE' AS complete_date,
    cpami_roc_to_date(r->>'COMPLETE_DATE') AS complete_date_date,
    r->>'Complete_permit_date' AS complete_permit_date,
    cpami_roc_to_date(r->>'Complete_permit_date') AS complete_permit_date_date,
    r->>'LICENSE' AS license,
    r->>'LICENSE_OLD' AS license_old,
    r->>'Start_work_permit_date' AS start_work_permit_date,
    cpami_roc_to_date(r->>'Start_work_permit_date') AS start_work_permit_date_date,
    r->>'Start_work_pre_date' AS start_work_pre_date,
    cpami_roc_to_date(r->>'Start_work_pre_date') AS start_work_pre_date_date,
    r->>'Worked' AS worked,
    r->>'Priced' AS priced,
    r->>'SEQ_NO' AS seq_no,
    r->>'Noticed_date' AS noticed_date,
    cpami_roc_to_date(r->>'Noticed_date') AS noticed_date_date,
    r->>'Noticed_Desc' AS noticed_desc,
    r->>'PS_DESC' AS ps_desc,
    r->>'LAST_MODIFY' AS last_modify,
    r->>'Lices_Flag' AS lices_flag,
    r->>'old_Index_key' AS old_index_key,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'CHG_EXP' AS chg_exp,
    r->>'CHG_PRIN' AS chg_prin,
    r->>'CHG_PRIN_DESC' AS chg_prin_desc,
    r->>'DOC1' AS doc1,
    r->>'DOC2' AS doc2,
    r->>'DOC3' AS doc3,
    r->>'DOC4' AS doc4,
    r->>'GOV' AS gov,
    r->>'BUILDING_KIND1_OLD' AS building_kind1_old,
    r->>'BUILDING_KIND2_OLD' AS building_kind2_old,
    r->>'BUILDING_KIND3_OLD' AS building_kind3_old,
    r->>'BUILDING_HEIGHT_OLD' AS building_height_old,
    NULLIF(r->>'BUILDING_HEIGHT_OLD', '')::numeric AS building_height_old_num,
    r->>'PRICE_OLD' AS price_old,
    NULLIF(r->>'PRICE_OLD', '')::numeric AS price_old_num,
    r->>'OTHERS_PRICE_OLD' AS others_price_old,
    NULLIF(r->>'OTHERS_PRICE_OLD', '')::numeric AS others_price_old_num,
    r->>'A12_TITTLE' AS a12_tittle,
    r->>'LICENSE_USE' AS license_use,
    r->>'IDENTIFY_LICE_DATE_USE' AS identify_lice_date_use,
    r->>'RECEIVE_LICE_DATE_USE' AS receive_lice_date_use,
    r->>'LAW_01' AS law_01,
    r->>'LAW_02' AS law_02,
    r->>'LAW_02_DOC' AS law_02_doc,
    r->>'LAW_03' AS law_03,
    r->>'IB0_CITY' AS ib0_city,
    r->>'A12_5TITLE' AS a12_5title,
    r->>'LICENSE_LINK' AS license_link,
    r->>'P01_LINK' AS p01_link,
    r->>'LAN_LINK' AS lan_link,
    r->>'ADDR_LINK' AS addr_link,
    r->>'LINE_LINK' AS line_link,
    r->>'LINK_TYPE' AS link_type,
    r->>'HADDR_LINK' AS haddr_link,
    r->>'HADDR_LIKK' AS haddr_likk,
    r->>'B13_3TYPE' AS b13_3type,
    r->>'B13_5TYPE' AS b13_5type,
    r->>'LAND_GET_TIME' AS land_get_time,
    r->>'FARM_MEMO' AS farm_memo,
    r->>'FARM_BUILD' AS farm_build,
    r->>'ADD_Priced' AS add_priced,
    r->>'CITY_BUD_KIND_OLD' AS city_bud_kind_old,
    r->>'CITY_BUD_KIND' AS city_bud_kind,
    r->>'CITY_PRICE_OLD' AS city_price_old,
    r->>'CITY_PRICE' AS city_price,
    r->>'CITY_BUILDING_HEIGHT' AS city_building_height,
    r->>'CITY_BUILDING_HEIGHT_OLD' AS city_building_height_old,
    r->>'LICLINK_1' AS liclink_1,
    r->>'LICLINK_2' AS liclink_2,
    r->>'TempBuild' AS tempbuild,
    r->>'I80BIN_1' AS i80bin_1,
    r->>'I80BIN_2' AS i80bin_2,
    r->>'I80BIN_3' AS i80bin_3,
    r->>'I80BIN_4' AS i80bin_4,
    r->>'I80BIN_5' AS i80bin_5,
    r->>'I80BIN_6' AS i80bin_6,
    r->>'I80BIN_7' AS i80bin_7,
    r->>'I80BIN_8' AS i80bin_8,
    r->>'I80BIN_9' AS i80bin_9,
    r->>'I80BIN_9_PER' AS i80bin_9_per,
    r->>'I80BIN_USE1' AS i80bin_use1,
    r->>'I80BIN_USE2' AS i80bin_use2,
    r->>'I80BIN_USE3' AS i80bin_use3,
    r->>'I80BIN_USE4' AS i80bin_use4,
    r->>'FIRESAVETY' AS firesavety,
    r->>'ISOPENAREA' AS isopenarea,
    r->>'CHGBUILDAREA' AS chgbuildarea,
    r->>'PARKFLOORSUM' AS parkfloorsum,
    r->>'GLVALUE' AS glvalue,
    r->>'DEVAREA1' AS devarea1,
    r->>'DEVAREA2' AS devarea2,
    r->>'DEVAREA3' AS devarea3,
    r->>'DEVAREA4' AS devarea4,
    r->>'DEVAREA5' AS devarea5,
    r->>'DEVAREA6' AS devarea6,
    r->>'DEVAREA7' AS devarea7,
    r->>'DEVAREA8' AS devarea8,
    r->>'DEVAREA9' AS devarea9,
    r->>'NFAREA1' AS nfarea1,
    r->>'NFAREA2' AS nfarea2,
    r->>'NFAREA3' AS nfarea3,
    r->>'NFAREA4' AS nfarea4,
    r->>'NFAREA5' AS nfarea5,
    r->>'NFAREA6' AS nfarea6,
    r->>'DX' AS dx,
    r->>'DY' AS dy,
    r->>'BUILD_ONE_PASS' AS build_one_pass,
    r->>'HOUSE_MEMO' AS house_memo
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSBASE'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bm_tec AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'PERSON_SEQ' AS person_seq,
    r->>'TEC_ITEM' AS tec_item,
    r->>'TEC_NAME' AS tec_name,
    r->>'TEC_TYPE' AS tec_type,
    r->>'CAPACITY_GET' AS capacity_get,
    r->>'CAPACITY_NO' AS capacity_no,
    r->>'TRX_NO' AS trx_no,
    r->>'REG_NO' AS reg_no,
    r->>'COM_NAME' AS com_name,
    r->>'COM_ZIP' AS com_zip,
    r->>'COM_ADDR' AS com_addr,
    r->>'COM_TEL' AS com_tel,
    r->>'COM_FAX' AS com_fax,
    r->>'PROGRAM' AS program,
    r->>'REG_DATE' AS reg_date,
    cpami_roc_to_date(r->>'REG_DATE') AS reg_date_date,
    r->>'MEMO' AS memo,
    r->>'TEC_DATA' AS tec_data,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BM_TEC'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmslan AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'SPOKESMAN' AS spokesman,
    r->>'DIST' AS dist,
    r->>'SECTION' AS section,
    r->>'ROAD_NO1' AS road_no1,
    r->>'ROAD_NO2' AS road_no2,
    r->>'TOT_AREA' AS tot_area,
    NULLIF(r->>'TOT_AREA', '')::numeric AS tot_area_num,
    r->>'USE_AREA' AS use_area,
    NULLIF(r->>'USE_AREA', '')::numeric AS use_area_num,
    r->>'USE_CATEGORY_CODE1' AS use_category_code1,
    r->>'USE_CATEGORY_CODE2' AS use_category_code2,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'SECTION_OLD' AS section_old,
    r->>'ROAD_NO1_OLD' AS road_no1_old,
    r->>'ROAD_NO2_OLD' AS road_no2_old,
    r->>'TOT_AREA_OLD' AS tot_area_old,
    NULLIF(r->>'TOT_AREA_OLD', '')::numeric AS tot_area_old_num,
    r->>'USE_AREA_OLD' AS use_area_old,
    NULLIF(r->>'USE_AREA_OLD', '')::numeric AS use_area_old_num,
    r->>'USE_CATEGORY_CODE1_OLD' AS use_category_code1_old,
    r->>'USE_CATEGORY_CODE2_OLD' AS use_category_code2_old,
    r->>'DIST_OLD' AS dist_old,
    r->>'LOCATED' AS located
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSLAN'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmslanowner AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'Person_seq' AS person_seq,
    r->>'DIST' AS dist,
    r->>'SECTION' AS section,
    r->>'ROAD_NO1' AS road_no1,
    r->>'ROAD_NO2' AS road_no2,
    r->>'owner_id' AS owner_id,
    r->>'owner' AS owner,
    r->>'TOT_AREA_hold' AS tot_area_hold,
    NULLIF(r->>'TOT_AREA_hold', '')::numeric AS tot_area_hold_num,
    r->>'USE_AREA_hold' AS use_area_hold,
    NULLIF(r->>'USE_AREA_hold', '')::numeric AS use_area_hold_num,
    r->>'owner_birth' AS owner_birth,
    cpami_roc_to_date(r->>'owner_birth') AS owner_birth_date,
    r->>'owner_add' AS owner_add,
    r->>'owner_tel' AS owner_tel,
    r->>'owner_memo' AS owner_memo,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSLANOWNER'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmsmemo AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'MEMO_SEQ' AS memo_seq,
    r->>'DESE' AS dese,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'MEMO_SEQ_NAME' AS memo_seq_name
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSMEMO'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmsp01 AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'SPOKESMAN' AS spokesman,
    r->>'BUILDING_NO' AS building_no,
    r->>'CHWANG' AS chwang,
    r->>'DONG' AS dong,
    r->>'FLOOR' AS floor,
    r->>'HOUSE' AS house,
    r->>'BLD_CODE1' AS bld_code1,
    r->>'BLD_CODE2' AS bld_code2,
    r->>'BLD_CODE3' AS bld_code3,
    r->>'BLD_CODE1_DESC' AS bld_code1_desc,
    r->>'BLD_CODE2_DESC' AS bld_code2_desc,
    r->>'BLD_CODE3_DESC' AS bld_code3_desc,
    r->>'CNAME' AS cname,
    r->>'BIRTH_DATE' AS birth_date,
    cpami_roc_to_date(r->>'BIRTH_DATE') AS birth_date_date,
    r->>'TEL_NO' AS tel_no,
    r->>'Fax_NO' AS fax_no,
    r->>'eMail' AS email,
    r->>'IDENTIFY_NO' AS identify_no,
    r->>'Law_represent' AS law_represent,
    r->>'O_ADDRADR' AS o_addradr,
    r->>'O_ADDRAD1' AS o_addrad1,
    r->>'O_ADDRAD2' AS o_addrad2,
    r->>'O_ADDRAD3' AS o_addrad3,
    r->>'O_ADDRAD4' AS o_addrad4,
    r->>'O_ADDRAD5' AS o_addrad5,
    r->>'O_ADDRAD6' AS o_addrad6,
    r->>'O_ADDRAD6_1' AS o_addrad6_1,
    r->>'O_ADDRAD7' AS o_addrad7,
    r->>'O_ADDRAD7_1' AS o_addrad7_1,
    r->>'O_ADDRAD8' AS o_addrad8,
    r->>'O_ADDRAD9' AS o_addrad9,
    r->>'H_ADDRADR' AS h_addradr,
    r->>'H_ADDRAD1' AS h_addrad1,
    r->>'H_ADDRAD2' AS h_addrad2,
    r->>'H_ADDRAD3' AS h_addrad3,
    r->>'H_ADDRAD4' AS h_addrad4,
    r->>'H_ADDRAD5' AS h_addrad5,
    r->>'H_ADDRAD6' AS h_addrad6,
    r->>'H_ADDRAD6_1' AS h_addrad6_1,
    r->>'H_ADDRAD7' AS h_addrad7,
    r->>'H_ADDRAD7_1' AS h_addrad7_1,
    r->>'H_ADDRAD8' AS h_addrad8,
    r->>'H_ADDRAD9' AS h_addrad9,
    r->>'ADDRADR' AS addradr,
    r->>'ADDRAD1' AS addrad1,
    r->>'ADDRAD2' AS addrad2,
    r->>'ADDRAD3' AS addrad3,
    r->>'ADDRAD4' AS addrad4,
    r->>'ADDRAD5' AS addrad5,
    r->>'ADDRAD6' AS addrad6,
    r->>'ADDRAD6_1' AS addrad6_1,
    r->>'ADDRAD7' AS addrad7,
    r->>'ADDRAD7_1' AS addrad7_1,
    r->>'ADDRAD8' AS addrad8,
    r->>'ADDRAD9' AS addrad9,
    r->>'CHKMARK' AS chkmark,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'CNAME_OLD' AS cname_old,
    r->>'BIRTH_DATE_OLD' AS birth_date_old,
    r->>'TEL_NO_OLD' AS tel_no_old,
    r->>'FAX_NO_OLD' AS fax_no_old,
    r->>'EMAIL_OLD' AS email_old,
    r->>'IDENTIFY_NO_OLD' AS identify_no_old,
    r->>'O_ADDRADR_OLD' AS o_addradr_old,
    r->>'O_ADDRAD1_OLD' AS o_addrad1_old,
    r->>'O_ADDRAD2_OLD' AS o_addrad2_old,
    r->>'O_ADDRAD3_OLD' AS o_addrad3_old,
    r->>'O_ADDRAD4_OLD' AS o_addrad4_old,
    r->>'O_ADDRAD5_OLD' AS o_addrad5_old,
    r->>'O_ADDRAD6_OLD' AS o_addrad6_old,
    r->>'O_ADDRAD6_1_OLD' AS o_addrad6_1_old,
    r->>'O_ADDRAD7_OLD' AS o_addrad7_old,
    r->>'O_ADDRAD7_1_OLD' AS o_addrad7_1_old,
    r->>'O_ADDRAD8_OLD' AS o_addrad8_old,
    r->>'O_ADDRAD9_OLD' AS o_addrad9_old,
    r->>'H_ADDRADR_OLD' AS h_addradr_old,
    r->>'H_ADDRAD1_OLD' AS h_addrad1_old,
    r->>'H_ADDRAD2_OLD' AS h_addrad2_old,
    r->>'H_ADDRAD3_OLD' AS h_addrad3_old,
    r->>'H_ADDRAD4_OLD' AS h_addrad4_old,
    r->>'H_ADDRAD5_OLD' AS h_addrad5_old,
    r->>'H_ADDRAD6_OLD' AS h_addrad6_old,
    r->>'H_ADDRAD6_1_OLD' AS h_addrad6_1_old,
    r->>'H_ADDRAD7_OLD' AS h_addrad7_old,
    r->>'H_ADDRAD7_1_OLD' AS h_addrad7_1_old,
    r->>'H_ADDRAD8_OLD' AS h_addrad8_old,
    r->>'H_ADDRAD9_OLD' AS h_addrad9_old,
    r->>'ADDRADR_OLD' AS addradr_old,
    r->>'ADDRAD1_OLD' AS addrad1_old,
    r->>'ADDRAD2_OLD' AS addrad2_old,
    r->>'ADDRAD3_OLD' AS addrad3_old,
    r->>'ADDRAD4_OLD' AS addrad4_old,
    r->>'ADDRAD5_OLD' AS addrad5_old,
    r->>'ADDRAD6_OLD' AS addrad6_old,
    r->>'ADDRAD6_1_OLD' AS addrad6_1_old,
    r->>'ADDRAD7_OLD' AS addrad7_old,
    r->>'ADDRAD7_1_OLD' AS addrad7_1_old,
    r->>'ADDRAD8_OLD' AS addrad8_old,
    r->>'ADDRAD9_OLD' AS addrad9_old,
    r->>'BUILDING_NO_OLD' AS building_no_old,
    r->>'CHWANG_OLD' AS chwang_old,
    r->>'DONG_OLD' AS dong_old,
    r->>'FLOOR_OLD' AS floor_old,
    r->>'HOUSE_OLD' AS house_old,
    r->>'BLD_CODE1_T' AS bld_code1_t,
    r->>'BLD_CODE2_T' AS bld_code2_t,
    r->>'BLD_CODE3_T' AS bld_code3_t
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSP01'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmsp02 AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'SPOKESMAN' AS spokesman,
    r->>'CNAME' AS cname,
    r->>'IDENTIFY_NO' AS identify_no,
    r->>'COM_ID_WORD' AS com_id_word,
    r->>'COM_ID_NO' AS com_id_no,
    r->>'COM_ID_NO1' AS com_id_no1,
    r->>'OFFICE_NAME' AS office_name,
    r->>'COM_ZIP' AS com_zip,
    r->>'COM_ADDRESS' AS com_address,
    r->>'TEL_NO' AS tel_no,
    r->>'FAX_NO' AS fax_no,
    r->>'eMail' AS email,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'COM_ID_AREA' AS com_id_area
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSP02'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmsp03 AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'SPOKESMAN' AS spokesman,
    r->>'CNAME' AS cname,
    r->>'IDENTIFY_NO' AS identify_no,
    r->>'COM_ID_WORD' AS com_id_word,
    r->>'COM_ID_NO' AS com_id_no,
    r->>'COM_ID_NO1' AS com_id_no1,
    r->>'OFFICE_NAME' AS office_name,
    r->>'COM_ZIP' AS com_zip,
    r->>'COM_ADDRESS' AS com_address,
    r->>'TEL_NO' AS tel_no,
    r->>'FAX_NO' AS fax_no,
    r->>'eMail' AS email,
    r->>'CHKMARK' AS chkmark,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'COM_ID_AREA' AS com_id_area,
    r->>'CNAME_OLD' AS cname_old,
    r->>'IDENTIFY_NO_OLD' AS identify_no_old,
    r->>'COM_ID_WORD_OLD' AS com_id_word_old,
    r->>'COM_ID_NO_OLD' AS com_id_no_old,
    r->>'COM_ID_NO1_OLD' AS com_id_no1_old,
    r->>'OFFICE_NAME_OLD' AS office_name_old,
    r->>'COM_ZIP_OLD' AS com_zip_old,
    r->>'COM_ADDRESS_OLD' AS com_address_old,
    r->>'TEL_NO_OLD' AS tel_no_old,
    r->>'FAX_NO_OLD' AS fax_no_old,
    r->>'EMAIL_OLD' AS email_old,
    r->>'COM_ID_AREA_OLD' AS com_id_area_old
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSP03'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmsp04 AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'SPOKESMAN' AS spokesman,
    r->>'COMPANY_NAME' AS company_name,
    r->>'COM_ZIP' AS com_zip,
    r->>'COM_ADDRESS' AS com_address,
    r->>'COM_IDNO' AS com_idno,
    r->>'BOSS' AS boss,
    r->>'ARC_REG_WORD' AS arc_reg_word,
    r->>'ARC_REG_CLAS' AS arc_reg_clas,
    r->>'ARC_REG_NO' AS arc_reg_no,
    r->>'CIV_REG_WORD' AS civ_reg_word,
    r->>'CIV_REG_NO' AS civ_reg_no,
    r->>'CIV_REG_SEQ_NO' AS civ_reg_seq_no,
    r->>'TECH_NAME' AS tech_name,
    r->>'TECH_IDNO' AS tech_idno,
    r->>'TECH_LIC' AS tech_lic,
    r->>'TEL_NO' AS tel_no,
    r->>'FAX_NO' AS fax_no,
    r->>'eMail' AS email,
    r->>'Io_Number' AS io_number,
    r->>'ARC_REG_PRI' AS arc_reg_pri,
    r->>'CHKMARK' AS chkmark,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'CLSRAN' AS clsran,
    r->>'COMPANY_NAME_OLD' AS company_name_old,
    r->>'COM_ZIP_OLD' AS com_zip_old,
    r->>'COM_ADDRESS_OLD' AS com_address_old,
    r->>'COM_IDNO_OLD' AS com_idno_old,
    r->>'BOSS_OLD' AS boss_old,
    r->>'CLSRAN_OLD' AS clsran_old,
    r->>'ARC_REG_WORD_OLD' AS arc_reg_word_old,
    r->>'ARC_REG_CLAS_OLD' AS arc_reg_clas_old,
    r->>'ARC_REG_NO_OLD' AS arc_reg_no_old,
    r->>'ARC_REG_PRI_OLD' AS arc_reg_pri_old,
    r->>'TECH_NAME_OLD' AS tech_name_old,
    r->>'TECH_LIC_OLD' AS tech_lic_old,
    r->>'TEL_NO_OLD' AS tel_no_old,
    r->>'FAX_NO_OLD' AS fax_no_old,
    r->>'EMAIL_OLD' AS email_old,
    r->>'SCTNAME' AS sctname,
    r->>'SCTNO' AS sctno,
    r->>'FTENGTYPE' AS ftengtype,
    r->>'GUILDNO1' AS guildno1,
    r->>'GUILDNO2' AS guildno2,
    r->>'SCTNAME_OLD' AS sctname_old,
    r->>'SCTNO_OLD' AS sctno_old,
    r->>'FTENGTYPE_OLD' AS ftengtype_old,
    r->>'GUILDNO1_OLD' AS guildno1_old,
    r->>'GUILDNO2_OLD' AS guildno2_old
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSP04'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmspark AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'PARK_KIND' AS park_kind,
    r->>'CAR_KIND' AS car_kind,
    r->>'APPL_KIND' AS appl_kind,
    r->>'IN_OUT' AS in_out,
    r->>'UP_DOWN' AS up_down,
    r->>'NUM' AS num,
    NULLIF(r->>'NUM', '')::numeric AS num_num,
    r->>'AREA' AS area,
    NULLIF(r->>'AREA', '')::numeric AS area_num,
    r->>'AIR_FLAG' AS air_flag,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSPARK'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmssc AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'識別碼' AS 識別碼,
    r->>'PRSTYLE' AS prstyle,
    r->>'LICENSE_OLD' AS license_old,
    r->>'P01_NAME' AS p01_name,
    r->>'P04_NAME' AS p04_name,
    r->>'P04_NO' AS p04_no,
    r->>'COST_PUB' AS cost_pub,
    r->>'COST_PUB_MAKING' AS cost_pub_making,
    r->>'COST_PRI_SELECT' AS cost_pri_select,
    r->>'COST_PRI' AS cost_pri,
    r->>'ZON_WORKING' AS zon_working,
    r->>'ZON_ZIP' AS zon_zip,
    r->>'DATE_WORK_START' AS date_work_start,
    r->>'DATE_WORK_END' AS date_work_end,
    r->>'DATE_USELIC' AS date_uselic,
    r->>'AREA_FLOOR' AS area_floor,
    r->>'AREA_UNDER_FLOOR' AS area_under_floor,
    r->>'FLOOR_COST' AS floor_cost,
    r->>'FLOOR_NUMBER' AS floor_number,
    r->>'PARK_INSIDE' AS park_inside,
    r->>'PARK_OUTSIDE' AS park_outside,
    r->>'BUC1' AS buc1,
    r->>'BUC2' AS buc2,
    r->>'BUC3' AS buc3,
    r->>'BUC4' AS buc4,
    r->>'BUC5' AS buc5,
    r->>'BUC6' AS buc6,
    r->>'BUC7' AS buc7,
    r->>'BUC8' AS buc8,
    r->>'BUC9' AS buc9,
    r->>'BUP1' AS bup1,
    r->>'BUP2' AS bup2,
    r->>'BUP3' AS bup3,
    r->>'BUP4' AS bup4,
    r->>'BUP5' AS bup5,
    r->>'BUP6' AS bup6,
    r->>'BUP7' AS bup7,
    r->>'BUP8' AS bup8,
    r->>'BUP9' AS bup9,
    r->>'BUP10' AS bup10,
    r->>'BUP11' AS bup11,
    r->>'BUK1' AS buk1,
    r->>'BUK2' AS buk2,
    r->>'BUK3' AS buk3,
    r->>'BUK4' AS buk4,
    r->>'BUK5' AS buk5,
    r->>'BUK6' AS buk6,
    r->>'BUS1' AS bus1,
    r->>'BUS2' AS bus2,
    r->>'BUS3' AS bus3,
    r->>'BUS4' AS bus4,
    r->>'PEO_TECH_DATE' AS peo_tech_date,
    cpami_roc_to_date(r->>'PEO_TECH_DATE') AS peo_tech_date_date,
    r->>'PEO_PLAIN_DATE' AS peo_plain_date,
    cpami_roc_to_date(r->>'PEO_PLAIN_DATE') AS peo_plain_date_date
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSSC'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmsstair AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'BUILDING_NO' AS building_no,
    r->>'STORY_CODE' AS story_code,
    r->>'USAGE_CODE1' AS usage_code1,
    r->>'USAGE_CODE2' AS usage_code2,
    r->>'USAGE_CODE3' AS usage_code3,
    r->>'USAGE_CODE1_DESC' AS usage_code1_desc,
    r->>'USAGE_CODE2_DESC' AS usage_code2_desc,
    r->>'USAGE_CODE3_DESC' AS usage_code3_desc,
    r->>'STORY_AREA' AS story_area,
    NULLIF(r->>'STORY_AREA', '')::numeric AS story_area_num,
    r->>'STORY_HEIGHT' AS story_height,
    NULLIF(r->>'STORY_HEIGHT', '')::numeric AS story_height_num,
    r->>'VERANDA_AREA' AS veranda_area,
    NULLIF(r->>'VERANDA_AREA', '')::numeric AS veranda_area_num,
    r->>'TERRACE_AREA' AS terrace_area,
    NULLIF(r->>'TERRACE_AREA', '')::numeric AS terrace_area_num,
    r->>'CHKMARK' AS chkmark,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'BUILDING_NO_OLD' AS building_no_old,
    r->>'STORY_CODE_OLD' AS story_code_old,
    r->>'USAGE_CODE1_OLD' AS usage_code1_old,
    r->>'USAGE_CODE2_OLD' AS usage_code2_old,
    r->>'USAGE_CODE3_OLD' AS usage_code3_old,
    r->>'STORY_AREA_OLD' AS story_area_old,
    NULLIF(r->>'STORY_AREA_OLD', '')::numeric AS story_area_old_num,
    r->>'STORY_HEIGHT_OLD' AS story_height_old,
    NULLIF(r->>'STORY_HEIGHT_OLD', '')::numeric AS story_height_old_num,
    r->>'VERANDA_AREA_OLD' AS veranda_area_old,
    NULLIF(r->>'VERANDA_AREA_OLD', '')::numeric AS veranda_area_old_num,
    r->>'TERRACE_AREA_OLD' AS terrace_area_old,
    NULLIF(r->>'TERRACE_AREA_OLD', '')::numeric AS terrace_area_old_num,
    r->>'USAGE_CODE1_DESC_OLD' AS usage_code1_desc_old,
    r->>'USAGE_CODE2_DESC_OLD' AS usage_code2_desc_old,
    r->>'USAGE_CODE3_DESC_OLD' AS usage_code3_desc_old,
    r->>'USAGE_CODE1_T' AS usage_code1_t,
    r->>'USAGE_CODE2_T' AS usage_code2_t,
    r->>'USAGE_CODE3_T' AS usage_code3_t,
    r->>'USAGE_CODE1_OLD_T' AS usage_code1_old_t,
    r->>'USAGE_CODE2_OLD_T' AS usage_code2_old_t,
    r->>'USAGE_CODE3_OLD_T' AS usage_code3_old_t,
    r->>'BUILDING_NO_TEAR' AS building_no_tear,
    r->>'STORY_CODE_TEAR' AS story_code_tear,
    r->>'USAGE_CODE1_TEAR' AS usage_code1_tear,
    r->>'USAGE_CODE2_TEAR' AS usage_code2_tear,
    r->>'USAGE_CODE3_TEAR' AS usage_code3_tear,
    r->>'STORY_AREA_TEAR' AS story_area_tear,
    NULLIF(r->>'STORY_AREA_TEAR', '')::numeric AS story_area_tear_num,
    r->>'STORY_HEIGHT_TEAR' AS story_height_tear,
    NULLIF(r->>'STORY_HEIGHT_TEAR', '')::numeric AS story_height_tear_num,
    r->>'VERANDA_AREA_TEAR' AS veranda_area_tear,
    NULLIF(r->>'VERANDA_AREA_TEAR', '')::numeric AS veranda_area_tear_num,
    r->>'TERRACE_AREA_TEAR' AS terrace_area_tear,
    NULLIF(r->>'TERRACE_AREA_TEAR', '')::numeric AS terrace_area_tear_num,
    r->>'USAGE_CODE1_DESC_TEAR' AS usage_code1_desc_tear,
    r->>'USAGE_CODE2_DESC_TEAR' AS usage_code2_desc_tear,
    r->>'USAGE_CODE3_DESC_TEAR' AS usage_code3_desc_tear,
    r->>'USAGE_CODE1_T_TEAR' AS usage_code1_t_tear,
    r->>'USAGE_CODE2_T_TEAR' AS usage_code2_t_tear,
    r->>'USAGE_CODE3_T_TEAR' AS usage_code3_t_tear
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSSTAIR'
) AS r;

CREATE OR REPLACE VIEW cpami_v_bmswork AS
SELECT
    d.case_id AS case_id,
    d.index_key AS index_key,
    d.form_set AS form_set,
    r->>'person_seq' AS person_seq,
    r->>'CONSNAME' AS consname,
    r->>'BUILDING_KIND' AS building_kind,
    r->>'LENGTH' AS length,
    NULLIF(r->>'LENGTH', '')::numeric AS length_num,
    r->>'HEIGHT' AS height,
    NULLIF(r->>'HEIGHT', '')::numeric AS height_num,
    r->>'WIDE' AS wide,
    NULLIF(r->>'WIDE', '')::numeric AS wide_num,
    r->>'AREA' AS area,
    NULLIF(r->>'AREA', '')::numeric AS area_num,
    r->>'CONNUM' AS connum,
    r->>'DESE' AS dese,
    r->>'CR_DATE' AS cr_date,
    cpami_roc_to_date(r->>'CR_DATE') AS cr_date_date,
    r->>'UP_DATE' AS up_date,
    cpami_roc_to_date(r->>'UP_DATE') AS up_date_date,
    r->>'OP_USER' AS op_user,
    r->>'識別碼' AS 識別碼,
    r->>'CONSNAME_OLD' AS consname_old,
    r->>'BUILDING_KIND_OLD' AS building_kind_old,
    r->>'LENGTH_OLD' AS length_old,
    NULLIF(r->>'LENGTH_OLD', '')::numeric AS length_old_num,
    r->>'HEIGHT_OLD' AS height_old,
    NULLIF(r->>'HEIGHT_OLD', '')::numeric AS height_old_num,
    r->>'WIDE_OLD' AS wide_old,
    NULLIF(r->>'WIDE_OLD', '')::numeric AS wide_old_num,
    r->>'AREA_OLD' AS area_old,
    NULLIF(r->>'AREA_OLD', '')::numeric AS area_old_num,
    r->>'DESE_OLD' AS dese_old
FROM cpami_case_documents AS d
CROSS JOIN LATERAL jsonb_array_elements(
    d.payload->'tables'->'BMSWORK'
) AS r;
